version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./bin/docker-init-db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - db:/var/lib/postgresql/data

  busybox:
    image: busybox
    command: /bin/chown -R 1000 /private-media
    volumes:
      - private_media:/private-media

  web:
    build: &web_build
      context: .
      args:
        RELEASE: ${TAG:-latest}
    image: clarityv2/website:${TAG:-latest}
    container_name: clarityv2
    environment:
      - DJANGO_SETTINGS_MODULE=clarityv2.conf.docker
      - SECRET_KEY=${SECRET_KEY:-7(h1r2hk)8z9+05edulo_3qzymwbo&c24=)qz7+_@3&2sp=u%i}
      - DB_NAME=clarity
      - DB_USER=clarity
      - DB_HOST=host.docker.internal
    volumes:
      - private_media:/app/private_media
      - .:/clarityv2
      - ./static:/clarityv2/static
    expose:
      - 8000
    depends_on:
      - db

  nginx:
    image: nginx
    volumes:
      - ./docker/nginx.default:/etc/nginx/conf.d/default.conf
      - ./static:/app/static
      - ./media:/app/media
      - private_media:/app/private_media
    ports:
      - "8000:80"
    depends_on:
      - web

volumes:
  db:
  private_media: