version: '3.8'

services:
  db:
    image: postgres:14
#    env_file:
#      - ../.env
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./bin/docker-init-db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - db:/var/lib/postgresql/data

  busybox:
    image: busybox
    command: /bin/chown -R 1000 /private-media
    volumes:
      - private_media:/private-media

  web:
    build: &web_build
      context: .
      args:
        RELEASE: ${TAG:-latest}
    image: clarityv2/website:${TAG:-latest}
    container_name: clarityv2
    environment:
      - DJANGO_SETTINGS_MODULE=clarityv2.conf.docker
      - SECRET_KEY=${SECRET_KEY:-7(h1r2hk)8z9+05edulo_3qzymwbo&c24=)qz7+_@3&2sp=u%i}
      - DB_NAME=clarity
      - DB_USER=clarity
      - DB_HOST=db
    volumes:
      - private_media:/app/private-media
#      - ..:/clarityv2
#      - ../static:/clarityv2/static
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db:
  private_media:

#  nginx:
#    image: nginx
#    volumes:
#    - ./nginx.default:/etc/nginx/conf.d/default.conf
#    - ../static:/clarityv2/static
##    environment:
##      - SERVER_NAME=localhost
##      - ROOT=/app
#    #command: bin/bash -c "envsubst "${SERVER_NAME} ${ROOT}" < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
#    ports:
#      - "8000:80"
#    depends_on:
#      - web