# Generated by Django 2.2.4 on 2019-12-14 14:14

import clarityv2.utils.storages
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('receipt', models.FileField(blank=True, storage=clarityv2.utils.storages.PrivateMediaFileSystemStorage(), upload_to='receipts/%Y/%m', verbose_name='receipt')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
            ],
            options={
                'verbose_name': 'deduction',
                'verbose_name_plural': 'deductions',
            },
        ),
    ]
