# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('phone', models.CharField(max_length=150, verbose_name='phone number')),
                ('address_street', models.CharField(blank=True, max_length=255, verbose_name='street')),
                ('house_number', models.CharField(blank=True, max_length=10, verbose_name='house number')),
                ('city', models.CharField(blank=True, max_length=64, verbose_name='city')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='country')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='postal code')),
                ('business_id', models.CharField(blank=True, max_length=50, verbose_name='business ID')),
                ('iban', models.CharField(blank=True, max_length=50, verbose_name='iban')),
            ],
            options={
                'verbose_name_plural': 'admin users',
                'verbose_name': 'admin user',
            },
        ),
    ]
