# Generated by Django 2.2.4 on 2019-09-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_adminuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='bank',
            field=models.CharField(blank=True, max_length=50, verbose_name='bank'),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=50, verbose_name='bank branch'),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='swift',
            field=models.CharField(blank=True, max_length=50, verbose_name='swift'),
        ),
    ]
