# Generated by Django 2.2.9 on 2020-01-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_adminuser_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='vat_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='VAT number'),
        ),
    ]
