# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-09 19:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_auto_20171108_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='date'),
        ),
    ]
