# Generated by Django 2.2.4 on 2019-12-17 19:11

from django.db import migrations
import privates.fields
import privates.storages


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_invoiceitem_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='pdf',
            field=privates.fields.PrivateMediaFileField(blank=True, storage=privates.storages.PrivateMediaFileSystemStorage(), upload_to='invoices/%Y/%m', verbose_name='pdf'),
        ),
    ]
