# Generated by Django 2.2.9 on 2020-01-31 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_auto_20200126_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='reference_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='reference number'),
        ),
    ]
