# Generated by Django 2.2.3 on 2019-07-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['pub_date'], 'verbose_name': 'blog post', 'verbose_name_plural': 'blog post'},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='publish_date'),
        ),
    ]
