# Generated by Django 2.2.3 on 2019-07-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190711_2145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['pub_date'], 'verbose_name': 'blog post', 'verbose_name_plural': 'blog posts'},
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='publish date'),
        ),
    ]
