# Generated by Django 2.2.3 on 2019-07-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190711_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
