# Generated by Django 2.2.4 on 2019-09-14 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190817_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-pub_date'], 'verbose_name': 'blog post', 'verbose_name_plural': 'blog posts'},
        ),
    ]
