# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 21:18
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_20161219_1914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='vat',
            new_name='vat_number',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tax_rate',
        ),
        migrations.AddField(
            model_name='project',
            name='vat',
            field=models.DecimalField(choices=[(Decimal('0.00'), 'no vat'), (Decimal('0.20'), 'standard vat rate')], decimal_places=2, default=Decimal('0.00'), max_digits=4, verbose_name='tax rate'),
        ),
        migrations.AlterField(
            model_name='client',
            name='country',
            field=django_countries.fields.CountryField(default='BE', max_length=2, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='client',
            name='language',
            field=models.CharField(choices=[('en', 'English')], default='nl', max_length=10, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='country',
            field=django_countries.fields.CountryField(default='BE', max_length=2, verbose_name='Country'),
        ),
    ]
