# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 20:54
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_auto_20171108_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='postal code'),
        ),
        migrations.AlterField(
            model_name='client',
            name='crn',
            field=models.CharField(blank=True, help_text='Business ID', max_length=50, verbose_name='registration number'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='label',
            field=models.CharField(blank=True, max_length=50, verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, verbose_name='phone number'),
        ),
    ]
