# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 18:24
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_auto_20171115_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='country',
            field=django_countries.fields.CountryField(default='NL', max_length=2, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='country',
            field=django_countries.fields.CountryField(default='NL', max_length=2, verbose_name='Country'),
        ),
    ]
