# Generated by Django 2.2.3 on 2019-07-11 17:54

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_auto_20171126_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='country',
            field=django_countries.fields.CountryField(default='FI', max_length=2, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='country',
            field=django_countries.fields.CountryField(default='FI', max_length=2, verbose_name='Country'),
        ),
    ]
