# Generated by Django 2.2.4 on 2019-09-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_auto_20190711_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='currency',
            field=models.CharField(choices=[('usd', 'USD'), ('euro', '€')], default='euro', max_length=20, verbose_name='currency'),
        ),
    ]
