# Generated by Django 2.2.9 on 2020-01-26 15:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_project_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='vat',
            field=models.DecimalField(choices=[(Decimal('0.00'), 'no vat'), (Decimal('0.24'), 'standard vat rate')], decimal_places=2, default=Decimal('0.00'), max_digits=4, verbose_name='tax rate'),
        ),
    ]
