name: Build static assets and deploy 
on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: build assets
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - run: npm ci
    - run: npm run build
    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        author_name: Alex K
        author_email: mail@example.com
        message: 'Your commit message'
        add: './src/clarityv2/static'
    - name: Install SSH Key
      uses: webfactory/ssh-agent@v0.6.0
      with:
        ssh-private-key: ${{ secrets.SSH_DEPLOY_KEY }}
    - name: Add remote
      run: git remote add live ${{ secrets.REMOTE }}
    - name: Deploy
      run: git push live master
